[project]
name = "spider"
version = "0.1.0"
requires-python = ">=3.12"

dependencies = [
    "selenium",
    "selenium-wire",
    "pandas",
    "requests",
    "sqlalchemy",
    "numpy",
    "blinker==1.6.2",
    "psycopg2-binary",
    "setuptools",         
    "packaging"           
]
